Added delete button (not working as good as possible)
spbu-math-cs/roomkn pull request #203
Opened 2023-11-19 16:32 UTC by PaulRalnikov

resolves #171

2023-11-19 17:53 UTC, darkfaeries approved these changes

2023-11-20 08:45 UTC, firelion9 requested changes

2023-11-20 08:45 UTC, firelion9 commented on client/src/pages/Room.css
А это тут что происходит? В css принят отступ 8 пробелов что ли?

2023-11-20 08:45 UTC, firelion9 commented on client/src/pages/UserReservation.css
> +    font-size: 20px;
И если там 8, почему здесь 4?

2023-11-20 08:45 UTC, firelion9 commented on client/src/pages/UserReservation.js
> +            setDeleteFinished(false)
Не, ну это надо будет переделать (не в этом pr, конечно)

2023-11-20 09:25 UTC, PaulRalnikov commented on client/src/pages/Room.css
Я не смог пофиксить отступы везде, оказалось, что в старом варианте кода даже в одном файле могло встретиться два варианта табуляции...

2023-11-20 09:26 UTC, PaulRalnikov commented on client/src/pages/UserReservation.js
> +            setDeleteFinished(false)
Да. И мне кажется, что переписывание на коллбеки – оверкилл, счётчиков вполне хватит

2023-11-20 12:39 UTC, firelion9 commented on client/src/pages/Room.css
Изменения-то тут откати)

2023-11-20 18:01 UTC, PaulRalnikov commented on client/src/pages/Room.css
Постараюсь, где найду

2023-11-20 18:28 UTC, firelion9 approved these changes

2023-11-20 18:32 UTC, merged