add GET /reserve with query params
spbu-math-cs/roomkn pull request #213
Opened 2023-11-23 21:03 UTC by makselivanov

2023-11-25 13:32 UTC, firelion9 requested changes

2023-11-25 13:32 UTC, firelion9 commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/ReservationsRouting.kt
> +        val untilResult = call.request.queryParameters["until"].toResultInstant(Clock.System.now() + 1.days)
Почему тут такой дефолт? Если правда нужен ровно 1 день, хотелось бы тут комментарий-пояснение (но вообще, я ведь могу зарезервировать и на +неделю, нет?)

2023-11-25 13:32 UTC, firelion9 commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/ReservationsRouting.kt
> +        val roomsIds = roomIdsString?.split(",")?.map { it.toIntOrNull() ?: return@get call.onMissingId() } ?: listOf()
`call.onMissingId()` ответит клиенту "id should be int", как-то не очень подходит по-моему

2023-12-08 01:27 UTC, makselivanov commented
Надо все же замержить изменения из main, там иначе все сломается, так что пока не мержим

2023-12-09 00:47 UTC, makselivanov commented
Если что, все замержил из main, все починил

2023-12-09 09:50 UTC, makselivanov commented on server/src/main/kotlin/org/tod87et/roomkn/server/database/Database.kt
> +        offset: Long = 0L
Потому что функция limit в Exposed sql принимает такие типы

2023-12-09 09:50 UTC, makselivanov commented on server/src/main/kotlin/org/tod87et/roomkn/server/database/DatabaseSession.kt
> +                    val fromCondition = if (from == null) Op.TRUE else (Reservations.until greater from)
Это специальные sql функции

2023-12-09 09:53 UTC, PaulRalnikov submitted a review, later dismissed

2023-12-09 10:29 UTC, firelion9 requested changes

2023-12-09 10:29 UTC, firelion9 commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/defaultResponses.kt
> +    respondText("offset should be int", status = HttpStatusCode.BadRequest)
Или всё-таки long?)

2023-12-09 10:29 UTC, firelion9 commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/ReservationsRouting.kt
> +                            .onSuccess {
Может проверить отдельно для каждого параметра и выйти из функции при ошибке? А то тут какой-то callback hell на ровном месте

2023-12-09 21:25 UTC, firelion9 approved these changes

2023-12-09 21:28 UTC, merged