Cool README.md
spbu-math-cs/roomkn pull request #222
Opened 2023-11-28 10:01 UTC by robozmey

2023-12-13 11:51 UTC, darkfaeries commented
картинку надо более новую поставить наверное, там кринж что резервацию делает юзер a, а в навбаре пишется Azat, сейчас уже нет этого бага

2023-12-19 16:57 UTC, darkfaeries commented
файла docker/README.md нету, сейчас на него ссылка есть общем readme

2023-12-19 17:06 UTC, darkfaeries requested changes
ссылки на демо, скриншоты и видео пока не работают, эти материалы точно загружены? ссылка на демо переадресовывает обратно на readme просто

2023-12-19 18:02 UTC, robozmey commented
> ссылки на демо, скриншоты и видео пока не работают, эти материалы точно загружены? ссылка на демо переадресовывает обратно на readme просто

Ссылку на демо добавил, скриншоты и видео добавим когда обновим интерфейс

2023-12-24 15:09 UTC, darkfaeries approved these changes

2023-12-24 15:12 UTC, merged