rewrite stateful api to callback api
spbu-math-cs/roomkn pull request #244
Opened 2023-11-28 21:47 UTC by darkfaeries

осталась админка, здесь в SignUp какие-то траблы, работает через раз
еще пофикшу

2023-11-29 11:40 UTC, robozmey requested changes
Нужно сделать для мержа:

- После создания резервации она не отображается на таймлайне, несмотря на то, что запрос GET /reservations был выполнен

- Так же при изменении даты таймлайн и даже новый запрос GET /reservations не кидается

Можно мерджить и без этого:

- В AdminPanelRooms после обновления, и после RESET востанавливаются данные до состояния до обновления. Хотя RESET нужен, чтобы востановить данные до последнего изменения.

- AdminPanelUsers не работает RESET на email

- В AdminPanelUsers вообще нет изменений для permission и крыжики всё ещё не кликаются

2023-11-29 11:40 UTC, robozmey commented on client/src/pages/admin/AdminUserList.js
> +        name: name,
name нужно заменить на username

2023-11-29 11:40 UTC, robozmey commented on client/src/pages/admin/AdminUserList.js
> +                <TextField sx={{maxWidth: "400px"}} label="Email" value={email}
Слишком маленькое растояние между полями

2023-12-04 12:59 UTC, darkfaeries commented on client/src/pages/admin/AdminUserList.js
> +                <TextField sx={{maxWidth: "400px"}} label="Email" value={email}
исправил

2023-12-04 13:01 UTC, darkfaeries commented
крыжики до сих пор не работают пока не нажать update, а так работают

2023-12-04 16:47 UTC, robozmey commented on client/src/pages/admin/AdminUserList.js
> +        name: name,
👍

2023-12-04 16:52 UTC, robozmey commented
> крыжики до сих пор не работают пока не нажать update, а так работают
А должно работать без update, но это не критично, в отдельной таске поправим

- Не работает DELETE на некоторых пользователях

2023-12-04 16:52 UTC, robozmey approved these changes
👍👍👍

2023-12-04 17:01 UTC, merged