Timeline in room list
spbu-math-cs/roomkn pull request #271
Opened 2023-12-09 22:22 UTC by PaulRalnikov

2023-12-10 18:10 UTC, robozmey requested changes
- Нужно, чтобы был один выбор промежутка на все таймлайны
- Имя комнаты передвинуть налево, как на картике

Было бы классно добавить рядом с выбором промежутка дат кнопки, которые бы меняли его на "Сегодня", "Завтра", "Текущая неделя", "Следующая неделя".

![image](https://github.com/spbu-math-cs/roomkn/assets/33569237/7d60d4d9-93e3-4ae8-b622-fac0a08b1d86)

2023-12-11 09:15 UTC, darkfaeries requested changes
1. В окне комнаты таймлайн заканчивается в 23:00 (чуть позже почему-то), а в списке комнат в 23:59, надо наверное одинаково, выбрать можно резервировать до 12 или конец в 11 и сделать везде так, предлагаю ограничить 23:00
2. Если выделить промежуток в много дат, непонятно где какая дата и какое время, возможно нужны какие-то пометки (особенно для дат, потому что если в какой-то день непонятно во сколько что-то начинается, можно просто зайти на страницу комнаты, а различать даты надо все-таки)
3. Согласен что надо налево скинуть название комнаты, ну либо просто побольше сделать
4. Не давать сделать дату from больше until? (хотя вроде пофиг, главное не вылетает)

2023-12-11 18:38 UTC, PaulRalnikov commented
Переделал расположение тайлайна и сделал общий выбор отрезка дат. Также теперь для единообразия на начало и конец таймлайна - это 00:00 соответствующих дней

2023-12-12 10:06 UTC, darkfaeries commented
> Переделал расположение тайлайна и сделал общий выбор отрезка дат. Также теперь для единообразия на начало и конец таймлайна - это 00:00 соответствующих дней

Есть разница между одним днем и несколькими, вот резервация в 9 утра сделана, почему-то если выбран 1 день, она идет с самого начала, а если 2, то с 00:00
![image](https://github.com/spbu-math-cs/roomkn/assets/112868256/43ab2eb8-ab48-4b39-a49c-87625a851c2a)
![image](https://github.com/spbu-math-cs/roomkn/assets/112868256/773eca67-42c1-46ff-b1bf-ae9a0c9a5afd)

2023-12-12 10:08 UTC, darkfaeries commented
как будто бы первый день меньше всех остальных занимает
![image](https://github.com/spbu-math-cs/roomkn/assets/112868256/e6c42638-034d-44bd-9fc6-a866624ae215)

2023-12-12 10:11 UTC, darkfaeries commented
> Переделал расположение тайлайна и сделал общий выбор отрезка дат. Также теперь для единообразия на начало и конец таймлайна - это 00:00 соответствующих дней

Проблема в том что в таймлайне отдельной комнаты границы 9:00 и 23:00, а в большом таймлайне теперь другие

2023-12-12 10:18 UTC, darkfaeries commented
Новый запрос reservations посылается при каждой смене границ, причем запрос всегда одинаковый, а фильтруется он на клиенте. Можно было бы хранить все резервации где-то на клиенте, после первого запроса при изменении границ просто перефильтровывать, мне кажется вроде несложно так переделать, хотя может я неправ

2023-12-12 10:19 UTC, PaulRalnikov commented
> Новый запрос reservations посылается при каждой смене границ, причем запрос всегда одинаковый, а фильтруется он на клиенте. Можно было бы хранить все резервации где-то на клиенте, после первого запроса при изменении границ просто перефильтровывать, мне кажется вроде несложно так переделать, хотя может я неправ

Думаю, все же посылать запрос к серверу заново - нормальная практика

2023-12-12 10:20 UTC, PaulRalnikov commented
> как будто бы первый день меньше всех остальных занимает ![image](https://private-user-images.githubusercontent.com/112868256/289821875-e6c42638-034d-44bd-9fc6-a866624ae215.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzU5ODksIm5iZiI6MTcwMjM3NTY4OSwicGF0aCI6Ii8xMTI4NjgyNTYvMjg5ODIxODc1LWU2YzQyNjM4LTAzNGQtNDRiZC05ZmM2LWE4NjY2MjRhZTIxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQxMDA4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTUyOGQwZTBhOWZiZGFhMjQ1MmI1ZjA2MDE1MjhlNzFjYmEzOGIyMDMxOTVmNTY5Njk5NzA4MmExY2MyMWM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o840iiOG6I0zbJwIkovI5R7JBPBqYEAWgJMOvkQnUfc)

Чет ты как будто изменения не докачал, сейчас все иначе выглядит
![image](https://github.com/spbu-math-cs/roomkn/assets/112890673/cc32c5e5-6bfc-4007-b08a-321871b57913)

2023-12-12 10:22 UTC, PaulRalnikov commented
> > Переделал расположение тайлайна и сделал общий выбор отрезка дат. Также теперь для единообразия на начало и конец таймлайна - это 00:00 соответствующих дней
> 
> Проблема в том что в таймлайне отдельной комнаты границы 9:00 и 23:00, а в большом таймлайне теперь другие

Да, есть немного. Но я пока не хочу от слова совсем ебаться с обрезанием каждого дня до отрезка [9:23] или что-то подобное, так как выглядит это все как оверкилл. Предлагаю пока забить, мб потом пофиксим этот момент

2023-12-12 10:28 UTC, darkfaeries commented
> > как будто бы первый день меньше всех остальных занимает ![image](https://private-user-images.githubusercontent.com/112868256/289821875-e6c42638-034d-44bd-9fc6-a866624ae215.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzU5ODksIm5iZiI6MTcwMjM3NTY4OSwicGF0aCI6Ii8xMTI4NjgyNTYvMjg5ODIxODc1LWU2YzQyNjM4LTAzNGQtNDRiZC05ZmM2LWE4NjY2MjRhZTIxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQxMDA4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTUyOGQwZTBhOWZiZGFhMjQ1MmI1ZjA2MDE1MjhlNzFjYmEzOGIyMDMxOTVmNTY5Njk5NzA4MmExY2MyMWM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o840iiOG6I0zbJwIkovI5R7JBPBqYEAWgJMOvkQnUfc)
> 
> Чет ты как будто изменения не докачал, сейчас все иначе выглядит ![image](https://private-user-images.githubusercontent.com/112890673/289825388-cc32c5e5-6bfc-4007-b08a-321871b57913.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzY3NTgsIm5iZiI6MTcwMjM3NjQ1OCwicGF0aCI6Ii8xMTI4OTA2NzMvMjg5ODI1Mzg4LWNjMzJjNWU1LTZiZmMtNDAwNy1iMDhhLTMyMTg3MWI1NzkxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQxMDIwNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NmE4NjA3MzI0MmY4NTVmZDRmNGQ0ZWU2MjRmZTI2OTVlNDBlZDNjMzYzY2VlODFiOWQ3ZjgwOGQzMTQyYTViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T7nTqlQTwAWlZGXa7wu0pvqCAfYwCMv3ZWvrlpyEzww)

да, я удалил коммент, не было последнего коммита

2023-12-12 10:29 UTC, darkfaeries commented
> > Новый запрос reservations посылается при каждой смене границ, причем запрос всегда одинаковый, а фильтруется он на клиенте. Можно было бы хранить все резервации где-то на клиенте, после первого запроса при изменении границ просто перефильтровывать, мне кажется вроде несложно так переделать, хотя может я неправ
> 
> Думаю, все же посылать запрос к серверу заново - нормальная практика

ну не знаю, я попробовал быстро менять дату с помощью ползунка, то есть быстро месяц или год менять, у меня жесть как залагало даже на локальной бд
часть этого - перерисовывание разделителей наверное, но и запросы свою роль играют думаю

2023-12-12 10:31 UTC, darkfaeries commented
> > Новый запрос reservations посылается при каждой смене границ, причем запрос всегда одинаковый, а фильтруется он на клиенте. Можно было бы хранить все резервации где-то на клиенте, после первого запроса при изменении границ просто перефильтровывать, мне кажется вроде несложно так переделать, хотя может я неправ
> 
> Думаю, все же посылать запрос к серверу заново - нормальная практика

мне кажется это была бы нормальная практика, если бы фильтрация запросов по дате была бы на сервере и запрос каждый раз был бы свой, но поскольку запрос один и тот же, это просто лишнее время, потому что сервер вернет то же самое

2023-12-12 10:32 UTC, PaulRalnikov commented
> > > Новый запрос reservations посылается при каждой смене границ, причем запрос всегда одинаковый, а фильтруется он на клиенте. Можно было бы хранить все резервации где-то на клиенте, после первого запроса при изменении границ просто перефильтровывать, мне кажется вроде несложно так переделать, хотя может я неправ
> > 
> > 
> > Думаю, все же посылать запрос к серверу заново - нормальная практика
> 
> ну не знаю, я попробовал быстро менять дату с помощью ползунка, то есть быстро месяц или год менять, у меня жесть как залагало даже на локальной бд часть этого - перерисовывание разделителей наверное, но и запросы свою роль играют думаю

Как вариант -- могу добавить отдельную кнопку update, но я считаю, что стоит это дело еще с кем-нибудь обсудить

2023-12-12 10:33 UTC, darkfaeries commented
> > > Переделал расположение тайлайна и сделал общий выбор отрезка дат. Также теперь для единообразия на начало и конец таймлайна - это 00:00 соответствующих дней
> > 
> > 
> > Проблема в том что в таймлайне отдельной комнаты границы 9:00 и 23:00, а в большом таймлайне теперь другие
> 
> Да, есть немного. Но я пока не хочу от слова совсем ебаться с обрезанием каждого дня до отрезка [9:23] или что-то подобное, так как выглядит это все как оверкилл. Предлагаю пока забить, мб потом пофиксим этот момент

это может броситься в глаза при демонстрации, что таймлайны разные в разных окнах
просто тут вопрос лучше сделать с 9 до 23 везде или с 0 до 24, потому что arguably если сразу видно много дней то странно начинать их с 9

2023-12-12 10:35 UTC, darkfaeries commented
> > > > Новый запрос reservations посылается при каждой смене границ, причем запрос всегда одинаковый, а фильтруется он на клиенте. Можно было бы хранить все резервации где-то на клиенте, после первого запроса при изменении границ просто перефильтровывать, мне кажется вроде несложно так переделать, хотя может я неправ
> > > 
> > > 
> > > Думаю, все же посылать запрос к серверу заново - нормальная практика
> > 
> > 
> > ну не знаю, я попробовал быстро менять дату с помощью ползунка, то есть быстро месяц или год менять, у меня жесть как залагало даже на локальной бд часть этого - перерисовывание разделителей наверное, но и запросы свою роль играют думаю
> 
> Как вариант -- могу добавить отдельную кнопку update, но я считаю, что стоит это дело еще с кем-нибудь обсудить

ну обновление страницы это update, при каждой загрузке ее запрос посылается в любом случае
так что отдельная кнопка вряд ли нужна

2023-12-12 10:35 UTC, PaulRalnikov commented
> > > > Переделал расположение тайлайна и сделал общий выбор отрезка дат. Также теперь для единообразия на начало и конец таймлайна - это 00:00 соответствующих дней
> > > 
> > > 
> > > Проблема в том что в таймлайне отдельной комнаты границы 9:00 и 23:00, а в большом таймлайне теперь другие
> > 
> > 
> > Да, есть немного. Но я пока не хочу от слова совсем ебаться с обрезанием каждого дня до отрезка [9:23] или что-то подобное, так как выглядит это все как оверкилл. Предлагаю пока забить, мб потом пофиксим этот момент
> 
> это может броситься в глаза при демонстрации, что таймлайны разные в разных окнах просто тут вопрос лучше сделать с 9 до 23 везде или с 0 до 24, потому что arguably если сразу видно много дней то странно начинать их с 9

Я считаю, что начинать дни с 9 утра в списке комнат -- идея говна, либо надо будет конкретно так подолбиться с дизайном (возможно, как-то дробить таймлайн или что-то подобное). Пока проще везде поставить 0 24

2023-12-12 10:36 UTC, PaulRalnikov commented
> > > > > Новый запрос reservations посылается при каждой смене границ, причем запрос всегда одинаковый, а фильтруется он на клиенте. Можно было бы хранить все резервации где-то на клиенте, после первого запроса при изменении границ просто перефильтровывать, мне кажется вроде несложно так переделать, хотя может я неправ
> > > > 
> > > > 
> > > > Думаю, все же посылать запрос к серверу заново - нормальная практика
> > > 
> > > 
> > > ну не знаю, я попробовал быстро менять дату с помощью ползунка, то есть быстро месяц или год менять, у меня жесть как залагало даже на локальной бд часть этого - перерисовывание разделителей наверное, но и запросы свою роль играют думаю
> > 
> > 
> > Как вариант -- могу добавить отдельную кнопку update, но я считаю, что стоит это дело еще с кем-нибудь обсудить
> 
> ну обновление страницы это update, при каждой загрузке ее запрос посылается в любом случае так что отдельная кнопка вряд ли нужна

Не, я про то, чтобы запрос посылался заново не при изменении дат, а только после нажатии на отдельную кнопку

2023-12-12 10:38 UTC, darkfaeries commented
> > > > > > Новый запрос reservations посылается при каждой смене границ, причем запрос всегда одинаковый, а фильтруется он на клиенте. Можно было бы хранить все резервации где-то на клиенте, после первого запроса при изменении границ просто перефильтровывать, мне кажется вроде несложно так переделать, хотя может я неправ
> > > > > 
> > > > > 
> > > > > Думаю, все же посылать запрос к серверу заново - нормальная практика
> > > > 
> > > > 
> > > > ну не знаю, я попробовал быстро менять дату с помощью ползунка, то есть быстро месяц или год менять, у меня жесть как залагало даже на локальной бд часть этого - перерисовывание разделителей наверное, но и запросы свою роль играют думаю
> > > 
> > > 
> > > Как вариант -- могу добавить отдельную кнопку update, но я считаю, что стоит это дело еще с кем-нибудь обсудить
> > 
> > 
> > ну обновление страницы это update, при каждой загрузке ее запрос посылается в любом случае так что отдельная кнопка вряд ли нужна
> 
> Не, я про то, чтобы запрос посылался заново не при изменении дат, а только после нажатии на отдельную кнопку

так а зачем заново посылать-то его при изменении дат?
запросы одинаковые все
я про то чтобы хранить все резервации что пришли, а фильтры просто говорят какие показывать а какие нет

2023-12-12 11:23 UTC, PaulRalnikov commented
> > > > > > > Новый запрос reservations посылается при каждой смене границ, причем запрос всегда одинаковый, а фильтруется он на клиенте. Можно было бы хранить все резервации где-то на клиенте, после первого запроса при изменении границ просто перефильтровывать, мне кажется вроде несложно так переделать, хотя может я неправ
> > > > > > 
> > > > > > 
> > > > > > Думаю, все же посылать запрос к серверу заново - нормальная практика
> > > > > 
> > > > > 
> > > > > ну не знаю, я попробовал быстро менять дату с помощью ползунка, то есть быстро месяц или год менять, у меня жесть как залагало даже на локальной бд часть этого - перерисовывание разделителей наверное, но и запросы свою роль играют думаю
> > > > 
> > > > 
> > > > Как вариант -- могу добавить отдельную кнопку update, но я считаю, что стоит это дело еще с кем-нибудь обсудить
> > > 
> > > 
> > > ну обновление страницы это update, при каждой загрузке ее запрос посылается в любом случае так что отдельная кнопка вряд ли нужна
> > 
> > 
> > Не, я про то, чтобы запрос посылался заново не при изменении дат, а только после нажатии на отдельную кнопку
> 
> так а зачем заново посылать-то его при изменении дат? запросы одинаковые все я про то чтобы хранить все резервации что пришли, а фильтры просто говорят какие показывать а какие нет

А, у нас пока фильтрация вся на фронте, я уж забыл... Тогда справедливо звучит. Но в будущем, думаю, стоит переделать но новый запрос к серверу, так как получать все резервации -- явно плохая затея

2023-12-12 22:14 UTC, robozmey approved these changes
На аппрув хватит

Есть баг - если менять год, то сначала оно ставит 0000 и пытается нарисовать все чёрточки на каждый день за 2000 лет. Это АРХИТЕКТУРНАЯ пробелма, нужно будет заменить везде TextField на DatePicker

Нужно будет - нарисовать чёрточки со временем
Кнопки - сегодня - завтра - текущая/следующая неделя

2023-12-13 10:44 UTC, darkfaeries approved these changes

2023-12-13 12:46 UTC, merged