Combine two Timelines in one
spbu-math-cs/roomkn pull request #322
Opened 2023-12-17 19:50 UTC by robozmey

2023-12-21 21:03 UTC, PaulRalnikov requested changes

2023-12-21 21:03 UTC, PaulRalnikov commented on client/src/pages/RoomScreenPage.js
> +import React from "react";
А для чего этот файл и где он используется?

2023-12-21 21:07 UTC, robozmey commented on client/src/pages/RoomScreenPage.js
> +import React from "react";
Для чего-то такого http://localhost:3000/scrn/3

![image](https://github.com/spbu-math-cs/roomkn/assets/33569237/0adbde7f-b24b-4330-b21d-424a20ad0727)

2023-12-21 21:26 UTC, robozmey commented on client/src/components/TimelineForRoomList.js
> +                        <Box className="reservation-user">
Убрано

2023-12-21 21:26 UTC, robozmey commented on client/src/components/TimelineForRoomList.js
> +                        <Box className="reservation-time">
Убрано

2023-12-21 21:27 UTC, PaulRalnikov commented on client/src/pages/RoomScreenPage.js
> +import React from "react";
Ок

2023-12-22 10:44 UTC, PaulRalnikov approved these changes

2023-12-22 14:00 UTC, merged