Reserve routing
spbu-math-cs/roomkn pull request #4
Opened 2023-10-02 23:02 UTC by firelion9

2023-10-02 23:21 UTC, makselivanov requested changes
Поменять одну тонкость

2023-10-02 23:21 UTC, makselivanov commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/ReserveRouting.kt
> +            call.respondText("Cannot process request", status = HttpStatusCode.BadRequest)
Считаю, что наверое лучше при ошибке непонятной возвращать 500 Internal Server Error

2023-10-03 06:30 UTC, firelion9 commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/ReserveRouting.kt
> +            call.respondText("Cannot process request", status = HttpStatusCode.BadRequest)
Ну почти, там вообще отлавливается ошибка десериализации тела запроса, но мы можем поймать и что-то другое

2023-10-03 20:10 UTC, makselivanov requested changes

2023-10-03 20:10 UTC, makselivanov commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/ReserveRouting.kt
> +            DatabaseFactory.database.createReservation(userId, roomId, from, until)
Теперь не понятно, что будет, если id комнаты не валидный или id пользователя, я бы сначала поменял бы базы данных

2023-10-08 16:25 UTC, makselivanov commented
Предлагаю полнотью закрыть этот пулл реквест из-за потери актуальности, но ветку пока не буду удалять соотвествествующую

2023-10-08 16:25 UTC, closed without merging