add interface for database
spbu-math-cs/roomkn pull request #53
Opened 2023-10-05 20:40 UTC by makselivanov

Сделал интерфейс для общения сервера к базе данных

2023-10-05 20:48 UTC, firelion9 requested changes

2023-10-05 20:48 UTC, firelion9 commented on server/src/main/kotlin/org/tod87et/roomkn/server/database/Database.kt
> +    fun getRoom(): Result<RoomInfo>
Думаю, тут потерян параметр у функции

2023-10-05 20:48 UTC, firelion9 commented on server/src/main/kotlin/org/tod87et/roomkn/server/database/Database.kt
> +    fun clear(): Unit //Clear database for TEST/DEBUG purpose
Давай без хвостовых комметариев, лучше перед функцией, возможно даже doc-comment'ом
```suggestion
    /** Clear database for TEST/DEBUG purpose */
    fun clear(): Unit
```

2023-10-05 20:48 UTC, firelion9 commented on server/src/main/kotlin/org/tod87et/roomkn/server/database/Database.kt
> +    fun getRoomReservation(roomId: Int): Result<List<Reservation>>
Множественное число

2023-10-05 21:04 UTC, firelion9 submitted a review, later dismissed

2023-10-06 20:37 UTC, Bupaheh requested changes

2023-10-06 20:37 UTC, Bupaheh commented on server/src/main/kotlin/org/tod87et/roomkn/server/database/Db.kt
> +class Db private constructor(private val database: Database): org.tod87et.roomkn.server.database.Database {
Don't use fully qualified name

2023-10-06 20:42 UTC, Bupaheh commented
And rename Db/Database. Db -> DatabaseImpl or something like that

2023-10-06 21:18 UTC, Bupaheh commented on server/src/main/kotlin/org/tod87et/roomkn/server/database/Db.kt
> +class Db private constructor(private val database: Database): org.tod87et.roomkn.server.database.Database {
ah, there is a name collision. Then Database -> Db, Db -> DbImpl

2023-10-07 14:44 UTC, firelion9 requested changes

2023-10-07 14:44 UTC, firelion9 commented on server/src/main/kotlin/org/tod87et/roomkn/server/database/Database.kt
> +import org.tod87et.roomkn.server.models.*
А что там у нас с запретом/разрешением звёздочек?

2023-10-07 14:44 UTC, firelion9 commented on server/src/main/kotlin/org/tod87et/roomkn/server/database/DatabaseSession.kt
> +class DatabaseSession private constructor(private val database: Database):
Прогони форматирование, тут пробел перед : должен быть

2023-10-07 14:44 UTC, firelion9 commented on server/src/main/kotlin/org/tod87et/roomkn/server/database/DatabaseSession.kt
> +    org.tod87et.roomkn.server.database.Database {
Мб всё-таки импорт (на это имя навесить alias RooMknDatabase или на 2ое ExposedDatabase)?

2023-10-07 18:58 UTC, firelion9 commented on server/src/main/kotlin/org/tod87et/roomkn/server/database/DatabaseSession.kt
> +    ExposedDatabase {
Так Eposed -- это же не эта, а другая, которая из  org.jetbrains.exposed.sql

2023-10-07 20:13 UTC, firelion9 approved these changes

2023-10-07 20:47 UTC, merged