Routes: minimal API functioanality
spbu-math-cs/roomkn pull request #61
Opened 2023-10-10 09:43 UTC by PaulRalnikov

2023-10-10 10:08 UTC, firelion9 requested changes
Вообще, по-хорошему, надо ещё подождать адекватных ошибок от бд. Но мы их уже неделю пинаем, так что их, думаю, будем поверх всего дописывать

2023-10-10 10:08 UTC, firelion9 commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/room.kt
> +    get("/rooms") {
Префикс /room можно вынести в верхнюю функцию (во всех 3ёх)

2023-10-10 10:08 UTC, firelion9 commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/room.kt
> +fun Route.rooms() {
private (все 3 функции)
И ещё пустая строка между функциями

2023-10-10 10:08 UTC, firelion9 commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/room.kt
> +                "",
И сообщение здесь тоже не лишнее x3

2023-10-10 14:35 UTC, makselivanov commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/ApiRouting.kt
> +        reserve()
добавь просто имена <path>Routing() для читаемости

2023-10-10 14:35 UTC, makselivanov commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/Reserve.kt
> +import io.ktor.server.routing.*
там еще можно сразу для ktor убрать галочку отдельную для *, которая в виде исключения

2023-10-10 14:37 UTC, makselivanov commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/room.kt
> +    get("/rooms") {
как раз через route все завернуть в твоей текущей функции Route.room,

2023-10-13 13:13 UTC, firelion9 requested changes
В getRooms надо бы заюзать параметры. Ну и ещё по мелочи

2023-10-13 13:13 UTC, firelion9 commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/ApiRouting.kt
> +private val database get() = DatabaseFactory.database
А тут зачем?

2023-10-13 13:13 UTC, firelion9 commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/room.kt
> +                "Room with this id not fount",
**is** not foun**d** :)
(И выше ещё 1 раз так же)

2023-10-13 13:13 UTC, firelion9 commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/Reserve.kt
> +                "Failed to add reservation: conflict with elder reservations",
older или other (elder это про братьев и волшебников)

2023-10-13 13:13 UTC, firelion9 commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/room.kt
> +private fun Route.roomId() {
Мб лучше что-нибудь типа `roomById`?

2023-10-13 13:13 UTC, firelion9 commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/room.kt
> +        val result = database.getRooms()
Sublist надо сделать однако

2023-10-13 13:28 UTC, firelion9 requested changes

2023-10-13 13:28 UTC, firelion9 commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/room.kt
> +            call.respond(HttpStatusCode.OK, it.subList(offset, offset + limit))
Не, тут ещё нужно, чтобы были индексы, корректные для it. На запросе с limit=5000 или offset=-1 так выдаст исключение

2023-10-13 13:58 UTC, firelion9 commented
Resovles #8

2023-10-13 14:48 UTC, firelion9 approved these changes

2023-10-13 17:37 UTC, makselivanov approved these changes

2023-10-13 17:37 UTC, makselivanov commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/room.kt
> +            call.respond(HttpStatusCode.OK,
Мы хотим тут тоже `return@get`?

2023-10-13 17:37 UTC, makselivanov commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/Reserve.kt
>              call.respond(HttpStatusCode.Created, it)
тут тоже нет `return`

2023-10-13 17:39 UTC, merged