Authorization
spbu-math-cs/roomkn pull request #65
Opened 2023-10-11 08:20 UTC by firelion9

Драфт для авторизации. Для запуска сервера нужно сгенерить общие секреты с помощью `generate-jwt-env.sh` и прописать их в environment. Пока что поддержки от БД нет, поэтому запросы к login будут валиться с not implemented.

2023-10-12 15:36 UTC, makselivanov commented on server/src/main/kotlin/org/tod87et/roomkn/server/database/Database.kt
>      fun loginUser(user: LoginUserInfo): Result<UserInfo>
Можно убрать за не надобностью

2023-10-12 15:36 UTC, makselivanov commented on server/src/main/kotlin/org/tod87et/roomkn/server/database/Database.kt
>      fun loginUser(user: LoginUserInfo): Result<UserInfo>
Я тут имел в виду loginUser

2023-10-24 15:49 UTC, makselivanov requested changes
Нашел, к чему придраться)

2023-10-24 15:49 UTC, makselivanov commented on server/src/main/kotlin/org/tod87et/roomkn/server/auth/AuthConfig.kt
> +        fun secret(secret: String) = apply { this.secret = Base64.getDecoder().decode(secret) }
Maybe add comment that String is encoded base64 string and with ByteArray is pure secret(for pepper too)

2023-10-24 18:27 UTC, firelion9 commented on server/script/generate-jwt-env.sh
Вроде сделал

2023-10-25 20:47 UTC, makselivanov submitted a review, later dismissed
Ну, вроде норм, можем мержить, я думаю

2023-10-26 10:02 UTC, PaulRalnikov approved these changes
Тесты прошли

2023-10-26 13:41 UTC, merged