#68: Database api v2
spbu-math-cs/roomkn pull request #69
Opened 2023-10-12 16:12 UTC by firelion9

resolves #68

2023-10-12 17:09 UTC, makselivanov requested changes
Мелкие исправления, после них будет approve от меня

2023-10-12 17:09 UTC, makselivanov commented on server/src/main/kotlin/org/tod87et/roomkn/server/models/LoginUserInfo.kt
> +    @SerialName("password") val password: String,
Тут SerialName можно убрать

2023-10-12 17:09 UTC, makselivanov commented on server/src/main/kotlin/org/tod87et/roomkn/server/models/RegistrationUserInfo.kt
> +class RegistrationUserInfo(
Можно наверное добавить

/** For internal use only. *Not* serializable */

2023-10-12 17:13 UTC, firelion9 commented on server/src/main/kotlin/org/tod87et/roomkn/server/models/RegistrationUserInfo.kt
> +class RegistrationUserInfo(
Можно

2023-10-13 11:28 UTC, makselivanov approved these changes

2023-10-13 12:04 UTC, merged