add respond to login
spbu-math-cs/roomkn pull request #92
Opened 2023-10-28 12:08 UTC by makselivanov

2023-10-28 12:11 UTC, Bupaheh requested changes

2023-10-28 12:11 UTC, Bupaheh commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/AccountRouting.kt
>      val env = environment!!
прокидывай исключение какое-нибудь нормальное

2023-10-28 12:19 UTC, Bupaheh commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/AccountRouting.kt
>      val env = environment!!
`val env = environment ?: error(TODO())`

2023-10-28 13:12 UTC, firelion9 commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/AccountRouting.kt
>      val env = environment!!
Не относится к текущему PR

2023-10-28 13:12 UTC, firelion9 approved these changes

2023-10-28 13:37 UTC, Bupaheh commented on server/src/main/kotlin/org/tod87et/roomkn/server/routing/AccountRouting.kt
>      val env = environment!!
ну прсто есть сомнения, что это когда-то пофиксится

2023-10-29 12:09 UTC, Bupaheh approved these changes

2023-10-29 13:37 UTC, merged